### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tahmidsadik** [tahmidsadik112/lyrics-scrapper-clojure#1]
- [x] Create Web Interface to see scraped lyrics before saving them to DB.
- [ ] Show song meta data before saving them.
- [ ] Add editing support to the scrapped lyrics and metadata to correct them before saving them to the DB.
- [ ] Create log for pages that does not work correctly with the current script code.
